[tool.ruff]
line-length = 72
target-version = "py312"
extend-include = ["*.ipynb"]

[tool.ruff.lint]
typing-modules = ["beartype.typing"]
select = [
  "E4", "E7", "E9",
  "F",
  "UP", # pyupgrade
  "I",   # isort
]
ignore = ["F722", "E741"]

[tool.ruff.lint.per-file-ignores]
"*.ipynb" = ["F401", "E731"]

[tool.ruff.lint.isort]
force-wrap-aliases = true
combine-as-imports = true

[tool.isort]
src_paths = ["onlineax"]
combine_as_imports = true
multi_line_output = 3
include_trailing_comma = true
